name: Publish package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install tsc
        run: npm install -g typescript@5.9.2
      - name: Set VERSION variable
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV
      - name: Authenticate to GitHub registry (deps)
        run: dotnet nuget update source github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Pack
        run: dotnet pack CleanUI -c Release --output packages /p:ContinuousIntegrationBuild=true /p:RepositoryBranch=${GITHUB_REF_NAME} /p:RepositoryCommit=${{ github.sha }} /p:Version=${VERSION}
      - name: Push packages to NuGet registry
        run: dotnet nuget push "packages/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key=${{secrets.NUGET_TOKEN}} --skip-duplicate
